name: Bug Report
description: File a report to help us improve
title: "[BUG]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: How to reproduce?
      description: Provide a link to a reproduction repository or code snippet if possible.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Library Version
      description: What version of @ismail-kattakath/mediapipe-react are you using?
      placeholder: e.g. 0.1.0
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: Framework
      options:
        - Next.js (App Router)
        - Next.js (Pages Router)
        - Vite + React
        - Create React App
        - Other
    validations:
      required: true
  - type: textarea
    id: browser-gpu-info
    attributes:
      label: Browser & GPU Information
      description: Since we use WebGPU/Web Assembly, please provide your browser version and GPU details.
      placeholder: |
        Browser: Chrome 120.0...
        GPU: NVIDIA RTX 4090 / Apple M2 Max
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
